<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-24T18:34:28 IST" name="Default suite" finished-at="2024-11-24T18:34:29 IST" duration-ms="252">
    <groups>
    </groups>
    <test started-at="2024-11-24T18:34:28 IST" name="Default test" finished-at="2024-11-24T18:34:29 IST" duration-ms="252">
      <class name="Framework.Eshopping.Potest">
        <test-method is-config="true" signature="createreports()[pri:0, instance:Framework.Eshopping.Potest@6bbe85a8]" started-at="2024-11-24T18:34:28 IST" name="createreports" finished-at="2024-11-24T18:34:28 IST" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createreports -->
        <test-method signature="placeOrder(java.util.HashMap,java.lang.String)[pri:0, instance:Framework.Eshopping.Potest@6bbe85a8]" started-at="2024-11-24T18:34:28 IST" name="placeOrder" data-provider="getData" finished-at="2024-11-24T18:34:29 IST" duration-ms="224" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void Framework.Eshopping.Potest.placeOrder(java.util.HashMap,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: placeOrder([java.util.HashMap<java.lang.String, java.lang.String> arg0, java.lang.String arg1])
Arguments: [(java.util.HashMap) {password=Test@1234, productName=ZARA COAT 3, username=satish@gmail.com}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Framework.Eshopping.Potest.placeOrder(java.util.HashMap,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: placeOrder([java.util.HashMap<java.lang.String, java.lang.String> arg0, java.lang.String arg1])
Arguments: [(java.util.HashMap) {password=Test@1234, productName=ZARA COAT 3, username=satish@gmail.com}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method signature="verifyProductDisplayInOrderPage()[pri:0, instance:Framework.Eshopping.Potest@6bbe85a8]" started-at="2024-11-24T18:34:29 IST" name="verifyProductDisplayInOrderPage" finished-at="2024-11-24T18:34:29 IST" depends-on-methods="Framework.Eshopping.Potest.placeOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Framework.Eshopping.Potest.verifyProductDisplayInOrderPage() on instance Framework.Eshopping.Potest@6bbe85a8 depends on not successfully finished methods 
[Framework.Eshopping.Potest.placeOrder() on instance Framework.Eshopping.Potest@6bbe85a8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Framework.Eshopping.Potest.verifyProductDisplayInOrderPage() on instance Framework.Eshopping.Potest@6bbe85a8 depends on not successfully finished methods 
[Framework.Eshopping.Potest.placeOrder() on instance Framework.Eshopping.Potest@6bbe85a8]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductDisplayInOrderPage -->
      </class> <!-- Framework.Eshopping.Potest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
